### ISSUE TITLE
No module named 'gradio'

### ISSUE THREAD

**Issue by djsuszi** [camenduru/Fooocus-docker#2]
after downloading models there is error:
```
100%|██████████| 32.1M/32.1M [00:00<00:00, 38.8MB/s]
  0%|          | 0.00/335M [00:00<?, ?B/s]Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_expansion.bin" to /content/test/models/prompt_expansion/fooocus_expansion/pytorch_model.bin

100%|██████████| 335M/335M [00:07<00:00, 45.6MB/s]
Traceback (most recent call last):
  File "/content/test/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/content/test/launch.py", line 147, in <module>
    from webui import *
  File "/content/test/webui.py", line 1, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
```

probably we need to install it in Dockerfile with pip command

**Comment by djsuszi** [comment]
when I'm adding gradio to pip install in Dockerfile I'm getting different error
```
Traceback (most recent call last):
  File "/content/test/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/content/test/launch.py", line 147, in <module>
    from webui import *
  File "/content/test/webui.py", line 12, in <module>
    import modules.gradio_hijack as grh
  File "/content/test/modules/gradio_hijack.py", line 18, in <module>
    from gradio.components.base import IOComponent, _Keywords
ImportError: cannot import name 'IOComponent' from 'gradio.components.base' (/usr/local/lib/python3.10/dist-packages/gradio/components/base.py)
```

I'm running it on Intel MacOS
